sudo: required
language: java
node_js:
- '6'
env:
- NODE_VERSION=6
addons:
  sonarqube:
    token:
      secure: IcidzMC74u+ePAHvZhYeSZo7VW7EXsRqLygTBOvGIo3r70fj5kvDTyFgBjBF2ZrBbGZ2DXTToguG67Q9AyBK4LNSdf+pwVx1nSXFbp5O144sze0pr4Lku1rL8x9ICB0mY7RlSlHTwpbz6xPbb1tJnepfvWZoTk+8qMwLpwCGtdVYQMq2EPdFgHXRFPdIykiBRbYF8pX4N1vuvellL7JcCObpXZ1NTqXcLMncObC2tywT6DwgKOPEDT8p5oZJ8TIeICbf14Qk7ubssw3EQR+iHE3PhTdYAGf0wsurWIK9ONzx/HNrnjVuj40xeTIA/B+khcU/4xEa1SF67X/6QgSsrGFoerA0OSpAAp+62PxJeS+I/FkhDz8N/6k9fAMEKyZH0BhFJIy2YVsmqI6Qv/XnN+NO30X3RiamADKRRtfP8X+DwGwZs7FYmadqNbpYaPpIewVfA6dpuH+eKT/NAL/jnPDvq9anwCKSJ86XgS34E5siNzbaWAZcRSsm4JP7FudPfikrLt1N1+rZbNetElb3l2xBp7+UxE6OzvKU77+/b80r/uCJLSoqYX7+dRI/ya4KxIbI9cd15YcouGUHCO7Zne7jNneD0SfUZss6hBRQB2VQjs7/KYynPBs9j8u6iYtYJhd33GHW7YHru9vl82Ul3qpPoiJ8SedvZolWtflqkDM=
jdk:
- oraclejdk8
install:
- nvm install $NODE_VERSION
- npm install
script:
- nvm use $NODE_VERSION
- npm test
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
deploy:
  provider: npm
  email: henriet@bubuabu.org
  api_key:
    secure: KuOg6fZzJKoGNpGVxO25OGjAON53iLMECE2R6hEkrsXxJormi4GknDGcqnl5zz147ohILG1R/3iZp1HkN+3jPiVUzFA7+6g7dPaIXEvuPUnrOlgPr0JWgGLDpUn8Uvm0FC3q71ZbDub7nn8bxfH+BITP0J8mofM8k0QeOyO1gpxoGbUcVN3bgET0YFuWUv8siCEW3Bd0WwquepOa5fXcSFYWgFDAvob1eivNYj2lcK4MidzlUsNJcvVvtGVcBWJbuswi68wmp+VmhMIwALSR966Ri/BMfgJlxHkrQVpsDulRPiX9lQvD0PHzSnS+GeizcaTx29hpaFILwaNR8jDLqCxBR1GFLmQlJm7KlR3t/lyzIrIdATzPS3dGhcjpVLCDmeWpWTYMbsEIyGg8EpdABNBCdLQ4xuDtmxznucAGfVIPew0kmwcHl3t1/SB4x7uzj/b1msjIy4mNxCNOqcXumTGwAE500Ntfw32nSBg1kHtnwKaRq6ojS1URH7aQFm7wd29BZfR1O1lQBZDdOWl+2NH0sfzcxl4VX4J/sZ0HOucsrqIngsWNhv1WDYKDeyu3Tvkd8yv08VFWgug4eJzCtOv6sYolzU52oMOrEhYGNYfTpVxVCqkWt5bR/LUtj4SY0YEBB0nn9EGs+bzR3Q5F3QpECh4uMfkzUxBTxG0SwF8=
  on:
    tags: true
    repo: BuBuaBu/babbybel
